apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: lockstore
spec:
  type: lock.redis
  version: v1
  metadata:
    - name: redisHost
      value: 172.29.20.171:6379
    - name: redisUsername
      value: "sargon_admin"
    - name: redisPassword
      value: "doyouloveme"